name: Deploy to Staging

# Only one workflow in a concurrency group may run at a time
concurrency:
  group: staging-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]

jobs:
  build-and-push-release-to-production:
    name: Build and push containers to auroraprodcr for Staging/Production
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    with:
      registry: auroraprodacr.azurecr.io
      image_name: robotics/sara-rain-drop-detector
      tag: ${{ github.event.release.tag_name }}
      secondary_tag: latest
    secrets:
      registry_username: ${{ secrets.ROBOTICS_AURORAPRODACR_USERNAME }}
      registry_password: ${{ secrets.ROBOTICS_AURORAPRODACR_PASSWORD }}

  deploy:
    name: Update deployment in Staging
    needs: [build-and-push-release-to-production]
    uses: equinor/armada/.github/workflows/update_kubernetes_deployment.yml@main
    with:
      environment: staging
      registry: auroraprodacr.azurecr.io
      image_name: robotics/sara-rain-drop-detector
      tag: ${{ github.event.release.tag_name }}
      author_name: ${{ github.event.release.author.login }}
      infrastructure_repository: equinor/analytics-infrastructure
    secrets:
      deploy_key: ${{ secrets.ANALYTICS_INFRASTRUCTURE_DEPLOY_KEY }}
